In [1]:
# import pandas
import pandas as pd

In [3]:
df = pd.read_csv('survey_results_schema.csv')

In [8]:
# calling the dataframe print a truncated version of it's contents
df

                Column                                       QuestionText
0           Respondent  Randomized respondent ID number (not in order ...
1           MainBranch  Which of the following options best describes ...
2             Hobbyist                            Do you code as a hobby?
3                  Age  What is your age (in years)? If you prefer not...
4           Age1stCode  At what age did you write your first line of c...
..                 ...                                                ...
56  WebframeWorkedWith  Which web frameworks have you done extensive d...
57       WelcomeChange  Compared to last year, how welcome do you feel...
58         WorkWeekHrs  On average, how many hours per week do you wor...
59           YearsCode  Including any education, how many years have y...
60        YearsCodePro  NOT including education, how many years have y...

[61 rows x 2 columns]

In [9]:
# head displays the first rows of a dataframe
df.head()
# head accepts an integer parameter to change the number of rows displayed

       Column                                       QuestionText
0  Respondent  Randomized respondent ID number (not in order ...
1  MainBranch  Which of the following options best describes ...
2    Hobbyist                            Do you code as a hobby?
3         Age  What is your age (in years)? If you prefer not...
4  Age1stCode  At what age did you write your first line of c...

In [10]:
# tail displays the last rows of a dataframe
df.tail()
# tail accepts an integer parameter to change the number of rows displayed

                Column                                       QuestionText
56  WebframeWorkedWith  Which web frameworks have you done extensive d...
57       WelcomeChange  Compared to last year, how welcome do you feel...
58         WorkWeekHrs  On average, how many hours per week do you wor...
59           YearsCode  Including any education, how many years have y...
60        YearsCodePro  NOT including education, how many years have y...